#!/usr/bin/python3

import socket
import configparser
from sshtunnel import SSHTunnelForwarder

config = configparser.ConfigParser()
config.read('firstboot_sys_client_config')

#Set Variables from config file

PORT = int(config['DEFAULT']['ServerPort'])  # The port used by the server
SERVER_IP = config['DEFAULT']['ServerIP']
SSH_USERNAME = config['SSH']['User']
SSH_PRIV_KEY = config['SSH']['SshPrivateKey']

ssh_tunnel = SSHTunnelForwarder(
    SERVER_IP,
    ssh_username=SSH_USERNAME,
    ssh_pkey=SSH_PRIV_KEY,
    #ssh_password="secret",
    local_bind_address=('127.0.0.1', PORT),
    remote_bind_address=('127.0.0.1', PORT)
)

ssh_tunnel.start()



HOST = "127.0.0.1"  # The server's hostname or IP address

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    s.sendall(b"Crank it boiii")
    data = s.recv(1024)

print(f"Received {data!r}")


ssh_tunnel.stop()
