#!/usr/bin/python3

import socketserver
from threading import Thread
from time import sleep


def listener():
    class MyTCPSocketHandler(socketserver.BaseRequestHandler):

        def handle(self):
            # self.request is the TCP socket connected to the client
            
            self.data = self.request.recv(1024).strip()
            if self.data.decode() == ":::::firstboot-sys-client:::::":
                print("client connected")
            else:
                print("client misconfigured")
                return
           
            c1 = client(12351515, 0, 0, 0, 0, 0, 0, 0, 0, 0)
            openclients.append(c1)

            self.request.sendall(":::::firstboot-server:::::".encode())

    if __name__ == "__main__":
    
        HOST, PORT = "localhost", 39045

        # instantiate the server, and bind to localhost on port 9999
        server = socketserver.ThreadingTCPServer((HOST, PORT), MyTCPSocketHandler)

        # activate the server
        # this will keep running until Ctrl-C
        server.serve_forever()

class client:
    def __init__(self, client_number, complete, hostname, ip_address, gateway, user, user_password, ssh_key, sudo_nopasswd, enable_root):
        self.client_number = client_number
        self.complete = complete
        self.hostname = hostname
        self.ip_address = ip_address
        self.gateway = gateway
        self.user = user
        self.user_password = user_password
        self.ssh_key = ssh_key
        self.sudo_nopasswd = sudo_nopasswd
        self.enable_root = enable_root
    
    def __str__(self):
        return str(self.client_number)
    def __repr__(self):
        return str(self.client_number)

openclients = []


t1 = Thread(target=listener)
t1.start()

while True:
    print(openclients)
    sleep(10)

